import { Talent } from '../types.ts';

const L = (row: number) => 1 + row * 4;
const T = 40;
const d = (r: number, c: number) => `d_r${r}c${c}`;

const base = (id: string, name: string, desc: string, x: number, y: number, max: number, level: number, rest: Partial<Talent> = {}): Talent => ({
  id,
  name,
  description: desc,
  points: 0,
  maxPoints: max,
  levelReq: level,
  cost: 1,
  icon: 'delapouite/bonsai-tree',
  gridX: x,
  gridY: y,
  ...rest,
});

export const DRUID_TALENTS: Talent[] = [
  base(d(0, 0), "Nature's Focus", 'Healing 2% per point.', 0, 0, 3, L(0), { icon: 'delapouite/ginkgo-leaf', statBonus: { healingBoost: 2 } }),
  base(d(0, 1), 'Furor', 'Max mana 45 per point.', 1, 0, 3, L(0), { icon: 'lorc/arcing-bolt', statBonus: { manaPool: 45 } }),
  base(d(0, 2), 'Verdant Heart', 'Haste 2% per point.', 2, 0, 2, L(0), { icon: 'lorc/wind-hole', statBonus: { haste: 2 } }),
  base(d(0, 3), "Wildseed Attunement", 'Crit 2% per point.', 3, 0, 2, L(0), { icon: 'delapouite/seedling', statBonus: { critChance: 2 } }),
  base(d(0, 4), 'Living Vine', 'Direct heals return 2 mana per point.', 4, 0, 2, L(0), { icon: 'lorc/roots', statBonus: { manaReturnOnDirectHeal: 2 } }),
  base(d(1, 0), 'Grove Harmony', 'Healing 3% per point.', 0, 1, 2, L(1), { prerequisites: [d(0, 0)], icon: 'delapouite/forest', statBonus: { healingBoost: 3 } }),
  base(d(1, 1), 'Tranquil Well', 'Max mana 60 per point.', 1, 1, 2, L(1), { prerequisites: [d(0, 1)], icon: 'lorc/heart-bottle', statBonus: { manaPool: 60 } }),
  base(d(1, 2), 'Naturalist', 'Unlocks Greater Heal.', 2, 1, 1, L(1), { prerequisites: [d(0, 2)], icon: 'delapouite/hand-of-god', spellId: 'greater_heal' }),
  base(d(1, 3), "Moonkin's Favor", 'Crit 2% per point.', 3, 1, 2, L(1), { prerequisites: [d(0, 3)], icon: 'lorc/owl', statBonus: { critChance: 2 } }),
  base(d(1, 4), 'Path of the Sprout', 'HoT tick healing +4% per point. Exclusive with Path of the Root.', 4, 1, 1, L(1), {
    prerequisites: [d(0, 4)],
    icon: 'lorc/leaf-orchid',
    statBonus: { healingBoost: 4 },
    exclusiveWith: [d(2, 4)],
    mechanicId: 'druid_path_sprout',
  }),
  base(d(2, 0), 'Barkskin Rite', 'Haste 2.5% per point.', 0, 2, 2, L(2), { prerequisites: [d(1, 0)], icon: 'lorc/tree-bark', statBonus: { haste: 2.5 } }),
  base(d(2, 1), 'Living Seed', 'Crit heals plant a seed; next damage to that ally heals for 15% of the original crit. Synergy: Natural Perfection.', 1, 2, 1, L(2), {
    prerequisites: [d(1, 1)],
    icon: 'delapouite/seedling',
    mechanicId: 'living_seed',
    synergyWith: [d(3, 1)],
  }),
  base(d(2, 2), 'Swiftmend', 'Unlocks Swiftmend. Consumes Rejuvenation or Regrowth on the target for a burst of healing.', 2, 2, 1, L(2), { prerequisites: [d(1, 2)], icon: 'lorc/fruiting', spellId: 'swiftmend' }),
  base(d(2, 3), 'Photosynthesis', 'While you have a HoT on yourself, haste 3% per point. Allies with your HoT have 2% more chance per point for HoT double ticks.', 3, 2, 1, L(2), { prerequisites: [d(1, 3)], icon: 'lorc/flowers', mechanicId: 'photosynthesis' }),
  base(
    d(2, 4),
    'Path of the Root',
    'Regrowth and Rejuvenation last 0.2s more per point worth of haste. Exclusive with Path of the Sprout.',
    4,
    2,
    1,
    L(2),
    { prerequisites: [d(0, 4)], icon: 'lorc/tap', exclusiveWith: [d(1, 4)], mechanicId: 'druid_path_root' },
  ),
  base(d(3, 0), 'Cenarion Bloom', 'Healing 4% per point.', 0, 3, 1, L(3), { prerequisites: [d(2, 0)], icon: 'lorc/cherry', statBonus: { healingBoost: 4 } }),
  base(
    d(3, 1),
    "Natural Perfection",
    'Each time you are hit, crit chance 2% for 10s, stacks 5. Synergy: Living Seed.',
    1,
    3,
    1,
    L(3),
    { prerequisites: [d(2, 1)], icon: 'lorc/surrounded-shield', mechanicId: 'natural_perfection', synergyWith: [d(2, 1)] },
  ),
  base(d(3, 2), "Nature's Bounty", 'Unlocks Wild Growth.', 2, 3, 1, L(3), { prerequisites: [d(2, 2)], icon: 'lorc/tornado', spellId: 'wild_growth' }),
  base(d(3, 3), 'Efflorescence', 'HoT healing 5% per point.', 3, 3, 2, L(3), { prerequisites: [d(2, 3)], icon: 'lorc/flower-tulip', statBonus: { healingBoost: 5 } }),
  base(d(3, 4), 'Emboldened Rejuvenation', 'Haste 3% per point.', 4, 3, 1, L(3), { prerequisites: [d(2, 4)], icon: 'lorc/vortex', statBonus: { haste: 3 } }),
  base(d(4, 0), 'Eternal Spring', 'Max mana 100.', 0, 4, 1, L(4), { prerequisites: [d(3, 0)], icon: 'lorc/water-bolt', statBonus: { manaPool: 100 } }),
  base(d(4, 1), 'Grovekeeper', 'Healing 6% per point.', 1, 4, 1, L(4), { prerequisites: [d(3, 1)], icon: 'delapouite/bonsai-tree', statBonus: { healingBoost: 6 } }),
  base(d(4, 2), 'Tree of Life', 'Tree of Life: your HoTs cost 30% less, direct heals cost 20% more while active. Toggle in combat (capstone).', 2, 4, 1, L(4), { prerequisites: [d(3, 2)], icon: 'delapouite/bonsai-tree', mechanicId: 'tree_of_life' }),
  base(d(4, 3), 'Verdant Infusion', 'Haste 4% per point.', 3, 4, 1, L(4), { prerequisites: [d(3, 3)], icon: 'lorc/compass', statBonus: { haste: 4 } }),
  base(d(4, 4), "Wildcrown's Boon", 'Crit 4% and mana +80.', 4, 4, 1, L(4), { prerequisites: [d(3, 4)], icon: 'lorc/pine-tree', statBonus: { critChance: 4, manaPool: 80 } }),
  base(d(5, 0), 'Heartwood Pact', 'Healing 5% and haste 3%.', 0, 5, 1, L(5), { prerequisites: [d(4, 0)], icon: 'lorc/broken-heart', statBonus: { healingBoost: 5, haste: 3 } }),
  base(d(5, 1), "Dreamwalker's Mending", 'Healing 5% per point.', 1, 5, 1, L(5), { prerequisites: [d(4, 1)], icon: 'lorc/drop', statBonus: { healingBoost: 5 } }),
  base(d(5, 2), 'Barkskin Mastery', 'Crit 4% and healing 3%.', 2, 5, 1, L(5), { prerequisites: [d(4, 2)], icon: 'lorc/wood-axe', statBonus: { critChance: 4, healingBoost: 3 } }),
  base(d(5, 3), 'Groveheart', 'Haste 5% and max mana 100.', 3, 5, 1, L(5), { prerequisites: [d(4, 3)], icon: 'lorc/giant', statBonus: { haste: 5, manaPool: 100 } }),
  base(d(5, 4), "Skylord's Bounty", 'Healing 4% and crit 3%.', 4, 5, 1, L(5), { prerequisites: [d(4, 4)], icon: 'lorc/visored-helm', statBonus: { healingBoost: 4, critChance: 3 } }),
  base(
    'd_cap',
    "Nature's Grace",
    'The ground around you flowers: passively heal all living allies a small amount each second for 20s. Visual bloom on your character.',
    2,
    6,
    1,
    T,
    {
      prerequisites: [d(5, 1), d(5, 2), d(5, 3)],
      icon: 'lorc/flowers',
      mechanicId: 'capstone_natures_grace',
      maxRankBonusDescription: 'Ground VFX and passive group healing.',
    },
  ),
];