import { Talent } from '../types.ts';

const L = (row: number) => 1 + row * 4;
const T = 40;
const h = (r: number, c: number) => `h_r${r}c${c}`;

const base = (id: string, name: string, desc: string, x: number, y: number, max: number, level: number, rest: Partial<Talent> = {}): Talent => ({
  id,
  name,
  description: desc,
  points: 0,
  maxPoints: max,
  levelReq: level,
  cost: 1,
  icon: 'lorc/crown',
  gridX: x,
  gridY: y,
  ...rest,
});

export const PALADIN_TALENTS: Talent[] = [
  base(h(0, 0), 'Divine Intellect', 'Max mana 55 per point.', 0, 0, 3, L(0), { icon: 'lorc/brain', statBonus: { manaPool: 55 } }),
  base(h(0, 1), 'Spiritual Focus', 'Haste 2% per point.', 1, 0, 2, L(0), { icon: 'lorc/wind-hole', statBonus: { haste: 2 } }),
  base(h(0, 2), 'Healing Light', 'Healing 3% per point.', 2, 0, 2, L(0), { icon: 'lorc/bright-explosion', statBonus: { healingBoost: 3 } }),
  base(h(0, 3), 'Sanctified Resilience', 'Crit 1.5% per point.', 3, 0, 2, L(0), { icon: 'lorc/target-dummy', statBonus: { critChance: 1.5 } }),
  base(h(0, 4), 'Infusion', 'Return 2 mana on direct heals per point.', 4, 0, 2, L(0), { icon: 'lorc/energy-shield', statBonus: { manaReturnOnDirectHeal: 2 } }),
  base(h(1, 0), 'Luminous Writ', 'Max mana 70 per point.', 0, 1, 2, L(1), { prerequisites: [h(0, 0)], icon: 'lorc/book-pile', statBonus: { manaPool: 70 } }),
  base(h(1, 1), 'Illumination', 'Critical heals restore 20% of the spell manacost, scaling with points.', 1, 1, 1, L(1), { prerequisites: [h(0, 1)], icon: 'lorc/light-bulb', mechanicId: 'illumination' }),
  base(h(1, 2), 'Divine Favor', 'Unlocks Greater Heal.', 2, 1, 1, L(1), { prerequisites: [h(0, 2)], icon: 'delapouite/hand-of-god', spellId: 'greater_heal' }),
  base(h(1, 3), "Crusader's Zeal", 'Healing 3% per point.', 3, 1, 2, L(1), { prerequisites: [h(0, 3)], icon: 'lorc/crossed-swords', statBonus: { healingBoost: 3 } }),
  base(h(1, 4), 'Path of the Dawn', 'Your wand applies Zeal. Exclusive with Path of the Dusk.', 4, 1, 1, L(1), {
    prerequisites: [h(0, 4)],
    icon: 'lorc/sunbeams',
    exclusiveWith: [h(2, 4)],
    mechanicId: 'pala_path_dawn',
  }),
  base(h(2, 0), 'Aegis of Devotion', 'Haste 2.5% per point.', 0, 2, 2, L(2), { prerequisites: [h(1, 0)], icon: 'delapouite/templar-shield', statBonus: { haste: 2.5 } }),
  base(h(2, 1), 'Tower of Radiance', 'Healing an ally under 50% health grants 1 Holy Power, max 3. Next direct heal is 100% stronger at 3.', 1, 2, 1, L(2), { prerequisites: [h(1, 1)], icon: 'lorc/tower-bridge', mechanicId: 'tower_of_radiance' }),
  base(h(2, 2), 'Holy Power', 'Unlocks Wild Growth.', 2, 2, 1, L(2), { prerequisites: [h(1, 2)], icon: 'lorc/tornado', spellId: 'wild_growth' }),
  base(h(2, 3), 'Judgment of the Pure', 'After using your wand, gain 8% haste for 6s, stacking to 2 per point in talent with duration.', 3, 2, 1, L(2), { prerequisites: [h(1, 3)], icon: 'lorc/hammer-drop', mechanicId: 'judgment_of_the_pure' }),
  base(
    h(2, 4),
    'Path of the Dusk',
    'Wand deals 1 more damage per point. Exclusive with Path of the Dawn.',
    4,
    2,
    1,
    L(2),
    { prerequisites: [h(0, 4)], icon: 'lorc/moon', exclusiveWith: [h(1, 4)], mechanicId: 'pala_path_dusk' },
  ),
  base(h(3, 0), 'Laying on Hands Rite', 'Healing 4% per point.', 0, 3, 1, L(3), { prerequisites: [h(2, 0)], icon: 'lorc/cross-flare', statBonus: { healingBoost: 4 } }),
  base(h(3, 1), 'Beacon of Light', '50% of your single-target healing on others is copied to the tank.', 1, 3, 1, L(3), { prerequisites: [h(2, 1)], icon: 'lorc/anchor', mechanicId: 'beacon_of_light' }),
  base(h(3, 2), "Light's Vigor", 'Crit 2% and healing 2% per point.', 2, 3, 2, L(3), { prerequisites: [h(2, 2)], icon: 'lorc/heart', statBonus: { critChance: 2, healingBoost: 2 } }),
  base(
    h(3, 3),
    'Cleanse the Wicked',
    'Heals have 8% more chance per point to remove a random debuff from the target. Synergy: Tower of Radiance.',
    3,
    3,
    1,
    L(3),
    { prerequisites: [h(2, 3)], icon: 'lorc/holy-oak', mechanicId: 'cleanse', synergyWith: [h(2, 1)] },
  ),
  base(h(3, 4), 'Avenger\'s Boon', 'Haste 3% and crit 2%.', 4, 3, 1, L(3), { prerequisites: [h(2, 4)], icon: 'lorc/wing-cloak', statBonus: { haste: 3, critChance: 2 } }),
  base(h(4, 0), 'Radiant Conviction', 'Max mana 120.', 0, 4, 1, L(4), { prerequisites: [h(3, 0)], icon: 'lorc/jeweled-chalice', statBonus: { manaPool: 120 } }),
  base(h(4, 1), 'Glimmering Promise', 'Healing 5% per point.', 1, 4, 1, L(4), { prerequisites: [h(3, 1)], icon: 'lorc/heart-inside', statBonus: { healingBoost: 5 } }),
  base(h(4, 2), "Light's Grace", 'Haste 4% and healing 3%.', 2, 4, 1, L(4), { prerequisites: [h(3, 2)], icon: 'lorc/lightsaber', statBonus: { haste: 4, healingBoost: 3 } }),
  base(h(4, 3), 'Hallowed Aegis', 'Healing 4% and crit 2%.', 3, 4, 1, L(4), { prerequisites: [h(3, 3)], icon: 'lorc/surrounded-shield', statBonus: { healingBoost: 4, critChance: 2 } }),
  base(h(4, 4), "Crusade's Fervor", 'Crit 3% and mana 90.', 4, 4, 1, L(4), { prerequisites: [h(3, 4)], icon: 'lorc/flag', statBonus: { critChance: 3, manaPool: 90 } }),
  base(h(5, 0), "Silver Hand's Mending", 'Haste 5% and max mana 100.', 0, 5, 1, L(5), { prerequisites: [h(4, 0)], icon: 'lorc/hand', statBonus: { haste: 5, manaPool: 100 } }),
  base(h(5, 1), "Argent Aegis", 'Healing 5% and crit 2%.', 1, 5, 1, L(5), { prerequisites: [h(4, 1)], icon: 'lorc/vortex', statBonus: { healingBoost: 5, critChance: 2 } }),
  base(h(5, 2), "Argent Vindicator", 'Healing 3% and haste 4%.', 2, 5, 1, L(5), { prerequisites: [h(4, 2)], icon: 'lorc/whip', statBonus: { healingBoost: 3, haste: 4 } }),
  base(h(5, 3), "Highlord's Gift", 'Crit 3% and healing 3%.', 3, 5, 1, L(5), { prerequisites: [h(4, 3)], icon: 'lorc/gold-bar', statBonus: { critChance: 3, healingBoost: 3 } }),
  base(h(5, 4), "Champion's Litany", 'Haste 3% and healing 3%.', 4, 5, 1, L(5), { prerequisites: [h(4, 4)], icon: 'lorc/violin', statBonus: { haste: 3, healingBoost: 3 } }),
  base(
    'h_cap',
    'Avenging Wrath',
    'Avenging Wrath: for 20s, 50% of your healing is dealt as damage to the nearest enemy. Gold aura on your character.',
    2,
    6,
    1,
    T,
    {
      prerequisites: [h(5, 1), h(5, 2), h(5, 3)],
      icon: 'lorc/angel-wings',
      mechanicId: 'capstone_avenging_wrath',
      maxRankBonusDescription: 'Gold glow and damage echo from healing.',
    },
  ),
];