import { Talent } from '../types.ts';

const L = (row: number) => 1 + row * 4;
const T = 40;

const base = (id: string, name: string, desc: string, x: number, y: number, max: number, level: number, rest: Partial<Talent> = {}): Talent => ({
  id,
  name,
  description: desc,
  points: 0,
  maxPoints: max,
  levelReq: level,
  cost: 1,
  icon: 'lorc/holy-grail',
  gridX: x,
  gridY: y,
  ...rest,
});

const pr = (r: number, c: number) => `p_r${r}c${c}`;

export const PRIEST_TALENTS: Talent[] = [
  base(
    pr(0, 0),
    'Divine Intellect',
    'Increases max mana by 40 per point. Max rank: +300 mana total from this talent.',
    0,
    0,
    3,
    L(0),
    {
      icon: 'lorc/brain',
      statBonus: { manaPool: 40 },
      maxRankBonusDescription: 'If maxed, regenerate 1% of total mana every 5 seconds in combat.',
    },
  ),
  base(
    pr(0, 1),
    'Mending Prose',
    'Increases all healing by 3% per point.',
    1,
    0,
    3,
    L(0),
    { icon: 'lorc/ball-heart', statBonus: { healingBoost: 3 } },
  ),
  base(
    pr(0, 2),
    'Improved Renew',
    'Renew ticks heal for 4% more per point.',
    2,
    0,
    3,
    L(0),
    { icon: 'lorc/heart-organ', statBonus: { healingBoost: 4 } },
  ),
  base(
    pr(0, 3),
    'Solemn Absolution',
    'Increases crit chance by 1.5% per point.',
    3,
    0,
    3,
    L(0),
    { icon: 'lorc/target-dummy', statBonus: { critChance: 1.5 } },
  ),
  base(
    pr(0, 4),
    'Benediction',
    'Return 3 flat mana on direct heals per point.',
    4,
    0,
    2,
    L(0),
    { icon: 'lorc/light-bulb', statBonus: { manaReturnOnDirectHeal: 3 } },
  ),
  base(
    pr(1, 0),
    'Harrowed Focus',
    'Increases haste by 2% per point.',
    0,
    1,
    2,
    L(1),
    { prerequisites: [pr(0, 0)], icon: 'lorc/wind-hole', statBonus: { haste: 2 } },
  ),
  base(
    pr(1, 1),
    'Gentle Absolution',
    'Increases all healing by 3% per point.',
    1,
    1,
    2,
    L(1),
    { prerequisites: [pr(0, 1)], icon: 'lorc/sun', statBonus: { healingBoost: 3 } },
  ),
  base(
    pr(1, 2),
    'Tome of Clarity',
    'Unlocks Greater Heal for your spellbook.',
    2,
    1,
    1,
    L(1),
    { prerequisites: [pr(0, 2)], icon: 'delapouite/holy-water', spellId: 'greater_heal' },
  ),
  base(
    pr(1, 3),
    'Chorus of Atonement',
    'Increases crit chance by 2% per point.',
    3,
    1,
    2,
    L(1),
    { prerequisites: [pr(0, 3)], icon: 'lorc/extra-lucid', statBonus: { critChance: 2 } },
  ),
  base(
    pr(1, 4),
    'Path of the Sun',
    'Path of the Sun: your heals are 3% more effective. Exclusive with Path of the Moon.',
    4,
    1,
    1,
    L(1),
    {
      prerequisites: [pr(0, 4)],
      icon: 'lorc/bright-explosion',
      statBonus: { healingBoost: 3 },
      exclusiveWith: [pr(2, 4)],
      mechanicId: 'path_sun',
    },
  ),
  base(
    pr(2, 0),
    'Resonant Words',
    'Increases haste by 2.5% per point.',
    0,
    2,
    2,
    L(2),
    { prerequisites: [pr(1, 0)], icon: 'lorc/echo-ripples', statBonus: { haste: 2.5 } },
  ),
  base(
    pr(2, 1),
    'Aegis of Faith',
    'Critical heals create a shield for 20% of the amount healed, lasting 10s.',
    1,
    2,
    2,
    L(2),
    { prerequisites: [pr(1, 1)], icon: 'lorc/energy-shield', mechanicId: 'divine_aegis' },
  ),
  base(
    pr(2, 2),
    'Rapture',
    'Increases all healing by 4% per point.',
    2,
    2,
    2,
    L(2),
    { prerequisites: [pr(1, 2)], icon: 'delapouite/holy-hand-grenade', statBonus: { healingBoost: 4 } },
  ),
  base(
    pr(2, 3),
    'Harsh Confession',
    'Flash Heal has 10% chance to make your next Greater Heal free and unimpeded by cooldown feel.',
    3,
    2,
    1,
    L(2),
    { prerequisites: [pr(1, 3)], icon: 'lorc/arcing-bolt', mechanicId: 'surge_of_light' },
  ),
  base(
    pr(2, 4),
    'Path of the Moon',
    'Path of the Moon: direct heals return 1% max mana. Exclusive with Path of the Sun.',
    4,
    2,
    1,
    L(2),
    {
      prerequisites: [pr(0, 4)],
      icon: 'lorc/moon',
      exclusiveWith: [pr(1, 4)],
      mechanicId: 'path_moon',
    },
  ),
  base(
    pr(3, 0),
    'Seraphic Boon',
    'Max mana +80 per point.',
    0,
    3,
    1,
    L(3),
    { prerequisites: [pr(2, 0)], icon: 'delapouite/jester-hat', statBonus: { manaPool: 80 } },
  ),
  base(
    pr(3, 1),
    'Binding Tether',
    'Your direct heals on allies also restore you for 6% of the value per point.',
    1,
    3,
    2,
    L(3),
    { prerequisites: [pr(2, 1)], icon: 'lorc/chained-heart', mechanicId: 'binding_heal' },
  ),
  base(
    pr(3, 2),
    'Hymn of the Choir',
    'Unlocks Wild Growth.',
    2,
    3,
    1,
    L(3),
    { prerequisites: [pr(2, 2)], icon: 'lorc/tornado', spellId: 'wild_growth' },
  ),
  base(
    pr(3, 3),
    'Luminous Aegis',
    'Shield strength from crits is 10% more effective per point.',
    3,
    3,
    2,
    L(3),
    { prerequisites: [pr(2, 3)], icon: 'lorc/surrounded-shield', statBonus: { healingBoost: 5 } },
  ),
  base(
    pr(3, 4),
    'Gleaming Proclamation',
    'Your Flash Heal has 5% more crit chance. Resonates with Harsh Confession.',
    4,
    3,
    1,
    L(3),
    {
      prerequisites: [pr(2, 3)],
      icon: 'lorc/lightning-tear',
      statBonus: { critChance: 5 },
      synergyWith: [pr(2, 3)],
    },
  ),
  base(
    pr(4, 0),
    'Fervor of the Martyr',
    'When a party member is below 30% health, your healing to them is 8% more per point.',
    0,
    4,
    2,
    L(4),
    { prerequisites: [pr(3, 0)], icon: 'lorc/candle-flame', statBonus: { healingBoost: 8 } },
  ),
  base(
    pr(4, 1),
    'Power Infusion',
    'Your next 3 heals after a critical heal are cast with 50% faster effective recovery.',
    1,
    4,
    1,
    L(4),
    { prerequisites: [pr(3, 1)], icon: 'lorc/extra-lucid', mechanicId: 'power_infusion' },
  ),
  base(
    pr(4, 2),
    'Spirit of Redemption',
    'When you drop below 30% health, your healing is increased 50% for 10s. 2 min internal cooldown.',
    2,
    4,
    1,
    L(4),
    { prerequisites: [pr(3, 2)], icon: 'lorc/angel-outfit', mechanicId: 'spirit_of_redemption' },
  ),
  base(
    pr(4, 3),
    'Celestial Reach',
    'Haste 4% per point.',
    3,
    4,
    2,
    L(4),
    { prerequisites: [pr(3, 3)], icon: 'delapouite/ascending-block', statBonus: { haste: 4 } },
  ),
  base(
    pr(4, 4),
    'Atonement Rite',
    'All healing 5% per point.',
    4,
    4,
    1,
    L(4),
    { prerequisites: [pr(3, 4)], icon: 'lorc/prayer', statBonus: { healingBoost: 5 } },
  ),
  base(
    pr(5, 0),
    'Crest of the Archon',
    'Max mana +120.',
    0,
    5,
    1,
    L(5),
    { prerequisites: [pr(4, 0)], icon: 'lorc/crown', statBonus: { manaPool: 120 } },
  ),
  base(
    pr(5, 1),
    'Hallowed Ground',
    'Healing 10% per point.',
    1,
    5,
    1,
    L(5),
    { prerequisites: [pr(4, 1)], icon: 'lorc/globe', statBonus: { healingBoost: 10 } },
  ),
  base(
    pr(5, 2),
    'Benedictory Echo',
    'Crit 6% per point.',
    2,
    5,
    1,
    L(5),
    { prerequisites: [pr(4, 2)], icon: 'delapouite/sparkles', statBonus: { critChance: 6 } },
  ),
  base(
    pr(5, 3),
    'Astral Harmony',
    'Haste 6% per point.',
    3,
    5,
    1,
    L(5),
    { prerequisites: [pr(4, 3)], icon: 'lorc/clockwork', statBonus: { haste: 6 } },
  ),
  base(
    pr(5, 4),
    'Final Benediction',
    'Crit 4% and healing 4% per point.',
    4,
    5,
    1,
    L(5),
    { prerequisites: [pr(4, 4)], icon: 'delapouite/perspective-dice-six-faces-random', statBonus: { critChance: 4, healingBoost: 4 } },
  ),
  base(
    'p_cap',
    'Archangel',
    'Archangel: for 15s, your direct heals echo to the whole party. Wings manifest on your bar.',
    2,
    6,
    1,
    T,
    {
      prerequisites: [pr(5, 1), pr(5, 2), pr(5, 3)],
      icon: 'lorc/crown',
      mechanicId: 'capstone_archangel',
      maxRankBonusDescription: 'Transforms combat visuals while active.',
    },
  ),
];
