package com.jdial.aegis.ui

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.widthIn
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.BasicText
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.jdial.aegis.data.Dungeon
import com.jdial.aegis.data.GameData
import com.jdial.aegis.sim.DungeonOutcome
import com.jdial.aegis.sim.DungeonOutcomeKind
import com.jdial.aegis.ui.theme.AegisType
import com.jdial.aegis.ui.theme.ForgedPanel
import com.jdial.aegis.ui.theme.Gilt
import com.jdial.aegis.ui.theme.GiltRule
import com.jdial.aegis.ui.theme.Ink
import com.jdial.aegis.ui.theme.LocalAccent
import com.jdial.aegis.ui.theme.Obsidian
import com.jdial.aegis.ui.theme.Vital
import kotlinx.coroutines.delay
import kotlin.random.Random

/** A dimmed, tap-to-dismiss ground for anything modal. */
@Composable
private fun Scrim(onDismiss: (() -> kotlin.Unit)?, content: @Composable () -> kotlin.Unit) {
    Box(
        Modifier
            .fillMaxSize()
            .background(Color.Black.copy(alpha = 0.72f))
            .then(if (onDismiss != null) Modifier.clickable(onClick = onDismiss) else Modifier),
        contentAlignment = Alignment.Center,
    ) {
        Box(Modifier.widthIn(max = 420.dp).padding(20.dp)) { content() }
    }
}

// --- dungeon queue ----------------------------------------------------------

/**
 * The pre-run sheet: pick a pace, wait for the group to fill, then enter.
 *
 * The queue fill is pure flavour — the party is generated by the engine on
 * entry — but it sets the tone and gives the pace choice somewhere to live.
 */
@Composable
fun DungeonQueueSheet(
    dungeon: Dungeon,
    data: GameData,
    onClose: () -> kotlin.Unit,
    onEnter: (pace: String) -> kotlin.Unit,
) {
    var pace by remember { mutableStateOf("normal") }
    var filled by remember(dungeon.id) { mutableIntStateOf(0) }

    LaunchedEffect(dungeon.id) {
        filled = 0
        repeat(4) {
            delay(350L + Random.nextLong(700))
            filled += 1
        }
    }
    val ready = filled >= 4

    Scrim(onDismiss = onClose) {
        ForgedPanel(Modifier.fillMaxWidth(), contentPadding = PaddingValues(18.dp)) {
            Column(horizontalAlignment = Alignment.CenterHorizontally) {
                GameIcon(dungeon.cardIcon, size = 46.dp, accent = Gilt.mid)
                Spacer(Modifier.height(10.dp))
                BasicText(
                    dungeon.name.uppercase(),
                    style = AegisType.title.copy(fontSize = 17.sp, textAlign = TextAlign.Center),
                )
                Spacer(Modifier.height(4.dp))
                BasicText("LV ${dungeon.levelMin}–${dungeon.levelMax}", style = AegisType.label)

                Spacer(Modifier.height(14.dp))
                GiltRule(Modifier.fillMaxWidth().height(1.dp))
                Spacer(Modifier.height(14.dp))

                BasicText("FORMING GROUP", style = AegisType.label.copy(color = Gilt.mid))
                Spacer(Modifier.height(8.dp))
                Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    // One slot for the tank, three for DPS; the healer is you.
                    repeat(4) { i ->
                        Box(
                            Modifier
                                .size(26.dp)
                                .clip(CircleShape)
                                .background(if (i < filled) Vital.healthy.copy(alpha = 0.75f) else Obsidian.abyss)
                                .border(
                                    1.dp,
                                    if (i < filled) Vital.healthy else Ink.muted.copy(alpha = 0.4f),
                                    CircleShape,
                                ),
                        )
                    }
                    Box(
                        Modifier
                            .size(26.dp)
                            .clip(CircleShape)
                            .background(LocalAccent.current.core.copy(alpha = 0.85f))
                            .border(1.dp, LocalAccent.current.bright, CircleShape),
                    )
                }

                Spacer(Modifier.height(16.dp))
                BasicText("PACE", style = AegisType.label.copy(color = Gilt.mid))
                Spacer(Modifier.height(8.dp))
                Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    listOf("fast", "normal", "slow").forEach { key ->
                        val def = data.pacing.paces.getValue(key)
                        PaceOption(
                            label = def.label,
                            xpMultiplier = def.xpMultiplier,
                            selected = pace == key,
                            modifier = Modifier.weight(1f),
                        ) { pace = key }
                    }
                }

                Spacer(Modifier.height(18.dp))
                if (ready) {
                    GiltButton("Enter Dungeon", onClick = { onEnter(pace) })
                } else {
                    BasicText("WAITING FOR GROUP…", style = AegisType.label.copy(color = Ink.muted))
                }
                Spacer(Modifier.height(10.dp))
                BasicText(
                    "CANCEL",
                    style = AegisType.label.copy(color = Ink.muted),
                    modifier = Modifier
                        .clip(RoundedCornerShape(4.dp))
                        .clickable(onClick = onClose)
                        .padding(horizontal = 14.dp, vertical = 8.dp),
                )
            }
        }
    }
}

@Composable
private fun PaceOption(
    label: String,
    xpMultiplier: Double,
    selected: Boolean,
    modifier: Modifier = Modifier,
    onClick: () -> kotlin.Unit,
) {
    val accent = LocalAccent.current
    val shape = RoundedCornerShape(5.dp)
    Column(
        modifier
            .clip(shape)
            .background(if (selected) Obsidian.raised else Obsidian.deep)
            .border(
                if (selected) 2.dp else 1.dp,
                if (selected) accent.core else Gilt.deep.copy(alpha = 0.45f),
                shape,
            )
            .clickable(onClick = onClick)
            .padding(vertical = 10.dp),
        horizontalAlignment = Alignment.CenterHorizontally,
    ) {
        BasicText(
            label.uppercase(),
            style = AegisType.label.copy(color = if (selected) Ink.primary else Ink.secondary),
        )
        Spacer(Modifier.height(3.dp))
        // The trade the player is actually making: speed against experience.
        BasicText(
            "${trimZeros(xpMultiplier)}× XP",
            style = AegisType.label.copy(fontSize = 9.sp, color = if (selected) accent.bright else Ink.muted),
        )
    }
}

private fun trimZeros(v: Double): String =
    if (v == v.toLong().toDouble()) v.toLong().toString() else v.toString()

// --- run outcome ------------------------------------------------------------

@Composable
fun OutcomeDialog(
    outcome: DungeonOutcome,
    data: GameData,
    onDismiss: () -> kotlin.Unit,
) {
    val success = outcome.kind == DungeonOutcomeKind.SUCCESS
    val dungeon = data.dungeon(outcome.dungeonId)
    val headline = when (outcome.kind) {
        DungeonOutcomeKind.SUCCESS -> "Dungeon Cleared"
        DungeonOutcomeKind.PARTY_WIPE -> "Party Wiped"
        DungeonOutcomeKind.HEALER_DOWN -> "You Fell"
    }
    val accentColor = if (success) Gilt.core else Vital.critical

    Scrim(onDismiss = null) {
        ForgedPanel(Modifier.fillMaxWidth(), contentPadding = PaddingValues(20.dp)) {
            Column(horizontalAlignment = Alignment.CenterHorizontally) {
                BasicText(
                    headline.uppercase(),
                    style = AegisType.title.copy(fontSize = 18.sp, color = accentColor),
                )
                if (dungeon != null) {
                    Spacer(Modifier.height(4.dp))
                    BasicText(dungeon.name.uppercase(), style = AegisType.label)
                }

                Spacer(Modifier.height(14.dp))
                GiltRule(Modifier.fillMaxWidth().height(1.dp))
                Spacer(Modifier.height(14.dp))

                StatRow("Experience", "+${outcome.xpGained}")
                StatRow("Healing done", outcome.stats.totalHealing.toInt().toString())
                StatRow("HPS", String.format("%.1f", outcome.stats.hps))
                StatRow("Overheal", "${outcome.stats.overhealPct.toInt()}%")
                StatRow("Healing per mana", String.format("%.2f", outcome.stats.hpm))

                Spacer(Modifier.height(20.dp))
                GiltButton("Continue", onClick = onDismiss)
            }
        }
    }
}

@Composable
private fun StatRow(label: String, value: String) {
    Row(
        Modifier.fillMaxWidth().padding(vertical = 4.dp),
        verticalAlignment = Alignment.CenterVertically,
    ) {
        BasicText(label.uppercase(), style = AegisType.label, modifier = Modifier.weight(1f))
        BasicText(value, style = AegisType.numeric.copy(fontSize = 14.sp))
    }
}
