// Generates parity/golden.json: the reference output of the JS engine, which the
// Kotlin port asserts against. Run with `node parity/generate-golden.mjs`.
//
// Keep this file free of randomness. Stochastic scenarios use the shared xorshift
// PRNG in parity/rng.mjs so both engines can replay identical sequences.
import { writeFileSync } from "node:fs";
import { Rng } from "./rng.mjs";
// Imported first: the module graph has a cycle between data/index.js and
// classes/index.js, and entering via the reducer is the order that resolves it.
import "../src/gameEngineReducer.js";
import {
  getPrimaryStats, getMaxMana, getHealingMultiplier, getUniqueStatRating,
  getSpellRank, getRankHealMult, getRankCostMult, getSpellUpgradeAtLevel,
  getTalentWeight, getSpiritRegenMultiplier, getMaxHealthForPool, getHealerMaxHealth
} from "../src/playerStats.js";
import {
  levelFromTotalXp, getXpToLevel, xpProgressWithinLevel,
  computeDungeonXpGain, computeDungeonFailureXpGain, buildSpellLoadout
} from "../src/gameStorage.js";
import {
  getBossDamageMultiplier, getEndlessMultiplier, getLevelGapDamageMultiplier,
  getTrashMaxHealth, getManaRegenPerSecond, manaRegenAmountPerTick,
  dungeonBaseXp, dungeonXpTierMultiplier
} from "../src/constants.js";
import { DUNGEONS } from "../src/data/index.js";
import { advanceCombatTick } from "../src/gameTick.js";
import { gameReducer } from "../src/gameEngineReducer.js";
import { ClassRegistry } from "../src/classes/index.js";

const CLASSES = ["PRIEST", "DRUID", "PALADIN"];
const LEVELS = [1, 2, 3, 5, 8, 13, 21, 30, 42, 55];

const round = (n) => (typeof n === "number" ? Math.round(n * 1e6) / 1e6 : n);

// Talents at zero points: the baseline every scenario shares.
const zeroTalents = (cls) =>
  ClassRegistry.getTalents(cls).map((t) => ({ ...t, points: 0 }));

const out = { note: "Generated by parity/generate-golden.mjs. Do not edit by hand." };

out.playerStats = {};
for (const cls of CLASSES) {
  const talents = zeroTalents(cls);
  out.playerStats[cls] = LEVELS.map((level) => {
    const { intellect, spirit } = getPrimaryStats(cls, level);
    return {
      level,
      intellect: round(intellect),
      spirit: round(spirit),
      maxMana: getMaxMana(cls, level, talents),
      healingMultiplier: round(getHealingMultiplier(cls, level, talents)),
      uniqueStatRating: round(getUniqueStatRating(cls, level, talents)),
      spiritRegenMultiplier: round(getSpiritRegenMultiplier(spirit)),
      healerMaxHealth: getHealerMaxHealth(cls, level),
      tankMaxHealth: getMaxHealthForPool("TANK", level, undefined),
      dpsMaxHealth: getMaxHealthForPool("DPS", level, undefined),
    };
  });
}

out.spellRanks = {};
for (const cls of CLASSES) {
  const order = ClassRegistry.getMetadata(cls).progression.spellOrder;
  out.spellRanks[cls] = {};
  for (const spellId of order) {
    out.spellRanks[cls][spellId] = LEVELS.map((level) => ({
      level,
      rank: getSpellRank(spellId, cls, level),
      healMult: round(getRankHealMult(getSpellRank(spellId, cls, level))),
      costMult: round(getRankCostMult(getSpellRank(spellId, cls, level))),
    }));
  }
  out.spellRanks[cls].__upgradesAtLevel = LEVELS.map((level) => ({
    level, ids: getSpellUpgradeAtLevel(cls, level),
  }));
}

out.talentWeight = [];
for (let maxPoints = 1; maxPoints <= 3; maxPoints += 1) {
  for (let points = 0; points <= maxPoints; points += 1) {
    out.talentWeight.push({ points, maxPoints, weight: round(getTalentWeight(points, maxPoints)) });
  }
}

out.xpCurve = [];
for (let level = 1; level <= 55; level += 1) {
  out.xpCurve.push({ level, cumulativeXp: getXpToLevel(level) });
}
out.levelFromXp = [0, 1, 100, 207, 500, 1000, 5000, 25000, 100000, 5000000]
  .map((xp) => ({ xp, level: levelFromTotalXp(xp), progress: xpProgressWithinLevel(xp) }));

out.dungeonScaling = DUNGEONS.map((d) => ({
  id: d.id,
  difficulty: d.difficulty,
  baseXp: dungeonBaseXp(d.difficulty),
  tierMultiplier: round(dungeonXpTierMultiplier(d.difficulty)),
  bossDamageMultiplier: round(getBossDamageMultiplier(d.difficulty)),
  trashMaxHealth: getTrashMaxHealth(d),
  xpAtLevelMin: computeDungeonXpGain(d, d.levelMin),
  xpAtLevelMaxPlus5: computeDungeonXpGain(d, d.levelMax + 5),
  failureXpTwoPulls: computeDungeonFailureXpGain(d, d.levelMin, 2),
}));

out.endlessMultiplier = [0, 1, 2, 5, 10, 25].map((s) => ({ stacks: s, mult: round(getEndlessMultiplier(s)) }));
out.levelGapMultiplier = [];
for (const gap of [-3, 0, 1, 2, 5, 10]) {
  out.levelGapMultiplier.push({ gap, mult: round(getLevelGapDamageMultiplier(10 + gap, 10)) });
}

out.manaRegen = [];
for (const cls of CLASSES) {
  for (const level of [1, 10, 30, 55]) {
    const { spirit } = getPrimaryStats(cls, level);
    out.manaRegen.push({
      cls, level,
      perSec: round(getManaRegenPerSecond(0, spirit)),
      perTick: round(manaRegenAmountPerTick(0, spirit)),
      lockedPerSec: round(getManaRegenPerSecond(5, spirit)),
    });
  }
}

out.spellLoadout = {};
for (const cls of CLASSES) {
  out.spellLoadout[cls] = buildSpellLoadout(cls, zeroTalents(cls));
}

// The shared PRNG. If these streams ever diverge, every stochastic scenario
// below is meaningless, so it is asserted first on the Kotlin side.
out.rngStreams = {};
for (const seed of [0, 1, 42, 1337, -7, 2147483647]) {
  const r = new Rng(seed);
  out.rngStreams[seed] = Array.from({ length: 12 }, () => r.next());
}
out.rngInts = {};
for (const seed of [3, 99]) {
  const r = new Rng(seed);
  out.rngInts[seed] = Array.from({ length: 10 }, () => r.nextInt(20, 50));
}


// --- combat tick scenarios --------------------------------------------------
//
// A fixed party and dungeon, advanced through the real tick loop with the shared
// PRNG. Party generation is NOT injectable in the JS engine (constants.js calls
// Math.random directly), so the party is pinned explicitly here instead and the
// Kotlin side rebuilds it from this same JSON.

function fixedParty(level) {
  const mk = (id, name, role, lv, maxHealth) => ({
    id, name, role, level: lv, health: maxHealth, maxHealth,
    buffs: [], debuffs: [], shield: 0, shieldTicksRemaining: 0, livingSeedPool: 0,
  });
  const tank = getMaxHealthForPool("TANK", level, undefined);
  const dps = getMaxHealthForPool("DPS", level, undefined);
  return [
    mk("1", "Tanky McShield", "TANK", level, tank),
    mk("2", "Zappy Mage", "DPS", level, dps),
    mk("3", "Hunter Mark", "DPS", Math.max(1, level - 1), getMaxHealthForPool("DPS", Math.max(1, level - 1), undefined)),
    mk("4", "Frostweaver", "DPS", level, dps),
    mk("5", "Player (You)", "HEALER", level, dps),
  ];
}

function snapshot(st) {
  return {
    tick: st.combatElapsedTicks,
    phase: st.combatPhase,
    trashPullsRemaining: st.trashPullsRemaining,
    enemyHealth: round(st.enemyHealth),
    mana: round(st.mana),
    progress: round(st.dungeonProgress),
    combatActive: st.isCombatActive,
    mechanicCooldown: st.mechanicCooldown,
    mechanicOrdinal: st.mechanicOrdinal,
    cooldowns: Object.keys(st.spellCooldowns).sort().map((k) => ({ id: k, t: st.spellCooldowns[k] })),
    playerBuffs: [...st.playerCombatBuffs].sort((a, b) => a.id.localeCompare(b.id))
      .map((b) => ({ id: b.id, ticks: b.remainingTicks, stacks: b.stacks ?? 0 })),
    bossBuffs: st.bossSelfBuffs.map((b) => ({ id: b.sourceAbilityId, ticks: b.remainingTicks })),
    healEffective: round(st.dungeonRunHealEffective),
    healOverheal: round(st.dungeonRunHealOverheal),
    xp: st.xp,
    level: st.level,
    outcome: st.dungeonOutcome ? st.dungeonOutcome.reason ?? st.dungeonOutcome.kind : null,
    outcomeXp: st.dungeonOutcome ? st.dungeonOutcome.xpGained : null,
    party: st.party.map((u) => ({
      id: u.id,
      health: round(u.health),
      shield: round(u.shield),
      buffs: u.buffs.map((b) => ({ src: b.sourceSpellId, ticks: b.remainingTicks })),
      debuffs: u.debuffs.map((d) => ({ src: d.sourceAbilityId, ticks: d.remainingTicks })),
    })),
  };
}

function buildScenarioState(cls, dungeonId, phase, talentRanks, level, jitter) {
  const dungeon = DUNGEONS.find((d) => d.id === dungeonId);
  const talents = zeroTalents(cls).map((t) => ({
    ...t,
    points: Math.min(t.maxPoints, talentRanks?.[t.id] ?? 0),
  }));
  const maxMana = getMaxMana(cls, level, talents);
  const trashHp = getTrashMaxHealth(dungeon);
  const isBoss = phase === "BOSS";
  return {
    playerClass: cls,
    level,
    xp: getXpToLevel(level),
    talentPoints: 0,
    talents,
    unlockedSpells: [],
    activeActionBars: [],
    completedDungeonIds: [],
    introTutorialComplete: true,
    tutorialCompletedSteps: [],
    party: fixedParty(level),
    mana: maxMana,
    maxMana,
    currentDungeon: dungeon,
    dungeonPace: "normal",
    dungeonProgress: isBoss ? 75 : 0,
    combatPhase: phase,
    trashPullsRemaining: isBoss ? 0 : 3,
    enemyHealth: isBoss ? dungeon.bossHealth : trashHp,
    enemyMaxHealth: isBoss ? dungeon.bossHealth : trashHp,
    isCombatActive: true,
    bossSelfBuffs: [],
    playerCombatBuffs: [],
    internalCooldowns: {},
    spellCooldowns: {},
    capstoneForm: null,
    holyPower: 0,
    beaconTargetId: "1",
    mechanicCooldown: 5,
    mechanicOrdinal: 0,
    combatElapsedTicks: 0,
    runDpsJitter: jitter ?? 1,
    endlessStacks: 0,
    manaPotionsUsedThisDungeon: 0,
    floatingCombatTexts: [],
    isTutorialPaused: false,
    dungeonOutcome: null,
    diagnostics: null,
    dungeonRunHealEffective: 0,
    dungeonRunHealOverheal: 0,
    dungeonRunManaSpentHealing: 0,
  };
}

// The first three run untalented. The rest invest in the mechanics that were
// dead before the hook repair, and cast on a fixed rotation, so the repaired
// code paths are genuinely exercised on both sides.
const TICK_SCENARIOS = [
  { name: "priest-deadmines-boss", cls: "PRIEST", dungeon: "deadmines", phase: "BOSS", seed: 42, ticks: 400 },
  { name: "druid-deadmines-trash", cls: "DRUID", dungeon: "deadmines", phase: "TRASH", seed: 7, ticks: 400 },
  { name: "priest-shadowfang-boss", cls: "PRIEST", dungeon: "shadowfang_keep", phase: "BOSS", seed: 1337, ticks: 300 },
  {
    name: "druid-talented-hots",
    cls: "DRUID", dungeon: "deadmines", phase: "BOSS", seed: 909, ticks: 500, level: 4,
    // Verdant Reservoir (HoT mana return), Cultivation, Deep Roots, Barkskin,
    // Harmony, Ramp haste/crit — every one of these was inert before.
    talents: { d_r0c4: 2, d_r2c0: 2, d_r4c3: 1, d_r5c4: 1 },
    rotation: { everyTicks: 12, spells: ["rejuvenation", "regrowth"] },
  },
  {
    name: "priest-talented-shields",
    cls: "PRIEST", dungeon: "deadmines", phase: "BOSS", seed: 5150, ticks: 500, level: 4,
    // Meditative Wellspring, self-shield DR, shield-maintenance haste.
    talents: { p_r0c4: 2, p_r3c3: 2, p_r5c3: 1 },
    rotation: { everyTicks: 10, spells: ["flash_heal", "renew"] },
  },
  {
    name: "paladin-talented-devotion",
    cls: "PALADIN", dungeon: "deadmines", phase: "BOSS", seed: 777, ticks: 500, level: 4,
    // Off-default so the per-run damage jitter is actually exercised.
    jitter: 0.97,
    rotation: { everyTicks: 10, spells: ["flash_heal", "holy_light"] },
  },
];

out.tickScenarios = TICK_SCENARIOS.map((sc) => {
  const initial = buildScenarioState(sc.cls, sc.dungeon, sc.phase, sc.talents, sc.level ?? 3, sc.jitter);
  const rng = new Rng(sc.seed);
  const random = rng.fn();
  let st = initial;
  const snapshots = [];
  const NOW = 1700000000000;
  let castIndex = 0;
  for (let i = 1; i <= sc.ticks; i += 1) {
    // Go through the reducer, not advanceCombatTick directly: the reducer is
    // what also ticks spell cooldowns, and it is what the app actually runs.
    st = gameReducer(st, { type: "TICK", random, now: NOW, ticksToProcess: 1 });
    if (!st.isCombatActive) { snapshots.push(snapshot(st)); break; }

    // A deterministic rotation: heal the lowest-health living ally.
    if (sc.rotation && i % sc.rotation.everyTicks === 0) {
      const living = st.party.filter((u) => u.health > 0);
      if (living.length > 0) {
        const target = living.reduce((a, b) =>
          a.health / a.maxHealth <= b.health / b.maxHealth ? a : b);
        const spellId = sc.rotation.spells[castIndex % sc.rotation.spells.length];
        castIndex += 1;
        st = gameReducer(st, {
          type: "CAST_SPELL",
          spellId,
          targetId: target.id,
          critRoll: random() * 100,
        });
      }
    }
    if (i % 20 === 0) snapshots.push(snapshot(st));
  }
  return {
    name: sc.name,
    cls: sc.cls,
    dungeonId: sc.dungeon,
    phase: sc.phase,
    seed: sc.seed,
    level: initial.level,
    maxMana: initial.maxMana,
    talents: sc.talents ?? {},
    jitter: sc.jitter ?? 1,
    rotation: sc.rotation ?? null,
    xp: initial.xp,
    party: initial.party.map((u) => ({
      id: u.id, name: u.name, role: u.role, level: u.level, maxHealth: u.maxHealth,
    })),
    mechanicCooldown: initial.mechanicCooldown,
    snapshots,
  };
});

writeFileSync(new URL("./golden.json", import.meta.url), JSON.stringify(out, null, 2) + "\n");
console.log("wrote parity/golden.json");
